### ISSUE TITLE
All covered OSS projects should be fully cacheable

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle-enterprise-oss-projects#23]
The following projects have been identified as not being fully cacheable:

- JUnit
- Spring Boot
- Micronaut
- Detekt
- OpenTelemetry
- JHipster
- Hibernate

We should consider providing PRs to make them fully cacheable.

This is a continuation of https://github.com/gradle/gradle-enterprise-oss-projects/pull/19

**Comment by jprinet** [comment]
- JUnit cache miss is a known issue (build time in `Manifest`)
- spring-boot cache miss is expected (`systemTest` task has `Task.upToDateWhen(false)`)

**Comment by etiennestuder** [comment]
> The following projects can be left as is:
> 
> * JHipster cache miss is a known issue (`generateGitProperties` has `Task.upToDateWhen(false)`)
> * JUnit cache miss is a known issue (build time in `Manifest`) and was already discussed with the team
> * spring-boot cache miss is expected (`systemTest` task has `Task.upToDateWhen(false)`)

@jprinet In this case, I suggest to mark these tasks explicitly as non-cacheable in their projects' builds.

**Comment by jprinet** [comment]
PR is ready for review
https://github.com/gradle/gradle-enterprise-oss-projects/pull/25

Still pending to be investigated
- Detekt (implicit task dependencies)
- OpenTelemetry (overlapping outputs)
- Hibernate (source files changed)

**Comment by jprinet** [comment]
OpenTelemetry outcome is 2 folded:
https://gradle.slack.com/archives/C02MJ0R7NLB/p1670924769869759

[known cache miss](https://github.com/gradle/playframework/issues/109) on Play Gradle plugin and some overlapping outputs.

We can leave the project with its cache misses for the moment and look into the Play Gradle plugin later

**Comment by jprinet** [comment]
Let's close this one for now

The projects for which the `failIfNotFullyCacheable` flag could not be turned on are:
- Opentelemetry
- Androidx
- Detekt
- Hibernate
- Micronaut
